# Generated by Django 4.1.10 on 2023-09-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='eid')),
                ('name', models.CharField(max_length=20, verbose_name='會員姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('gender', models.CharField(max_length=5, verbose_name='性別')),
                ('email', models.EmailField(max_length=50, verbose_name='電子信箱')),
                ('address', models.CharField(max_length=50, verbose_name='通訊住址')),
                ('birth', models.DateField(verbose_name='生日')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='uid')),
                ('name', models.CharField(max_length=20, verbose_name='會員姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('gender', models.CharField(max_length=5, verbose_name='性別')),
                ('email', models.EmailField(max_length=50, verbose_name='電子信箱')),
                ('address', models.CharField(max_length=50, verbose_name='通訊住址')),
                ('birth', models.DateField(verbose_name='生日')),
                ('allergen', models.CharField(blank=True, max_length=30, verbose_name='過敏原')),
            ],
        ),
        migrations.CreateModel(
            name='MemberP',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('upid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_maintenance.member')),
                ('account', models.CharField(max_length=50, verbose_name='帳號')),
                ('password', models.CharField(max_length=100, verbose_name='密碼')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeP',
            fields=[
                ('epid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_maintenance.employee')),
                ('account', models.CharField(max_length=50, verbose_name='帳號')),
                ('password', models.CharField(max_length=100, verbose_name='密碼')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('sid', models.CharField(max_length=50, verbose_name='商店編號')),
                ('upid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_maintenance.member')),
                ('type', models.CharField(max_length=30, verbose_name='食物類型')),
                ('name', models.CharField(max_length=50, verbose_name='店家名稱')),
                ('intro', models.CharField(max_length=50, verbose_name='店家簡介')),
                ('area', models.CharField(max_length=40, verbose_name='所在區域')),
                ('address', models.CharField(max_length=50, verbose_name='店家地址')),
                ('lng', models.FloatField(verbose_name='經度')),
                ('lat', models.FloatField(verbose_name='緯度')),
                ('link', models.CharField(max_length=50, null=True, verbose_name='社群連結')),
                ('on_business', models.BooleanField(verbose_name='是否營業')),
            ],
        ),
        migrations.CreateModel(
            name='Store_open',
            fields=[
                ('stid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_maintenance.store')),
                ('Mon_time_B', models.TimeField(blank=True, verbose_name='周一開始')),
                ('Mon_time_N', models.TimeField(blank=True, verbose_name='周一結束')),
                ('Tue_time_B', models.TimeField(blank=True, verbose_name='周二開始')),
                ('Tue_time_N', models.TimeField(blank=True, verbose_name='周二結束')),
                ('Wed_time_B', models.TimeField(blank=True, verbose_name='周三開始')),
                ('Wed_time_N', models.TimeField(blank=True, verbose_name='周三結束')),
                ('Thu_time_B', models.TimeField(blank=True, verbose_name='周四開始')),
                ('Thu_time_N', models.TimeField(blank=True, verbose_name='周四結束')),
                ('Fri_time_B', models.TimeField(blank=True, verbose_name='周五開始')),
                ('Fri_time_N', models.TimeField(blank=True, verbose_name='周五結束')),
                ('Sat_time_B', models.TimeField(blank=True, verbose_name='周六開始')),
                ('Sat_time_N', models.TimeField(blank=True, verbose_name='周六結束')),
                ('Sun_time_B', models.TimeField(blank=True, verbose_name='周日開始')),
                ('Sun_time_N', models.TimeField(blank=True, verbose_name='周日結束')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='備註')),
            ],
        ),
    ]
