# Generated by Django 4.1.10 on 2023-09-22 07:54

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_maintenance', '0002_memberp_is_verified_alter_memberp_account'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='memberp',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
