# Generated by Django 4.1.10 on 2023-10-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maintenance', '0002_alter_store_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='link',
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='電子信箱'),
        ),
        migrations.AddField(
            model_name='store',
            name='link_fb',
            field=models.CharField(max_length=100, null=True, verbose_name='社群連結_FB'),
        ),
        migrations.AddField(
            model_name='store',
            name='link_ig',
            field=models.CharField(max_length=100, null=True, verbose_name='社群連結_IG'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='店家電話'),
        ),
        migrations.AlterField(
            model_name='store',
            name='area',
            field=models.CharField(max_length=40, null=True, verbose_name='所在區域'),
        ),
        migrations.AlterField(
            model_name='store',
            name='intro',
            field=models.CharField(max_length=50, null=True, verbose_name='店家簡介'),
        ),
    ]
