# Generated by Django 4.1.10 on 2023-10-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maintenance', '0003_remove_store_link_store_email_store_link_fb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=40, null=True, verbose_name='所在都市'),
        ),
    ]
