# Generated by Django 4.1.10 on 2023-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maintenance', '0006_alter_store_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='prefer',
            field=models.CharField(max_length=50, null=True, verbose_name='偏好飲食'),
        ),
    ]
