# Generated by Django 4.1.10 on 2023-10-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=30, verbose_name='商品編號')),
                ('type', models.CharField(max_length=30, verbose_name='食物類型')),
                ('name', models.CharField(max_length=30, verbose_name='商品名稱')),
                ('intro', models.CharField(max_length=50, verbose_name='商品簡介')),
                ('food_pic', models.ImageField(upload_to='', verbose_name='商品照片')),
                ('price', models.SmallIntegerField(verbose_name='價格')),
                ('ingredient', models.CharField(max_length=200, verbose_name='食物使用成分')),
                ('allergen', models.CharField(max_length=200, verbose_name='過敏原成分')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_maintenance.store')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('evaid', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='留言編號')),
                ('star', models.IntegerField(verbose_name='分數')),
                ('explain', models.CharField(blank=True, max_length=100, verbose_name='心得或改進')),
                ('upid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
            ],
        ),
    ]
