# Generated by Django 4.1.10 on 2023-10-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actid', models.CharField(max_length=40, verbose_name='活動編號')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='活動標頭')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('upload_date', models.DateField(verbose_name='發文時間')),
                ('down_date', models.DateField(verbose_name='下架時間')),
                ('content', models.CharField(blank=True, max_length=100000, verbose_name='活動內文')),
                ('status', models.BooleanField(default=True, verbose_name='是否上架')),
                ('pic1', models.ImageField(height_field=1080, null=True, upload_to='activity/', verbose_name='首圖', width_field=1080)),
                ('pic2', models.ImageField(height_field=1080, null=True, upload_to='activity/', verbose_name='一張', width_field=1080)),
                ('pic3', models.ImageField(height_field=1080, null=True, upload_to='activity/', verbose_name='二張', width_field=1080)),
                ('pic4', models.ImageField(height_field=1080, null=True, upload_to='activity/', verbose_name='三張', width_field=1080)),
            ],
        ),
    ]
