# Generated by Django 4.1.10 on 2023-10-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pic1',
            field=models.ImageField(height_field='400', null=True, upload_to='activity/', verbose_name='首圖', width_field='400'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pic2',
            field=models.ImageField(height_field='400', null=True, upload_to='activity/', verbose_name='一張', width_field='400'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pic3',
            field=models.ImageField(height_field='400', null=True, upload_to='activity/', verbose_name='二張', width_field='400'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pic4',
            field=models.ImageField(height_field='400', null=True, upload_to='activity/', verbose_name='三張', width_field='400'),
        ),
    ]
