# Generated by Django 4.1.10 on 2023-10-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('data_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=50, verbose_name='訂單編號')),
                ('order_time', models.DateTimeField(verbose_name='訂購時間')),
                ('complete_time', models.DateTimeField(verbose_name='完成時間')),
                ('total', models.CharField(max_length=50, verbose_name='訂單總額')),
                ('status', models.CharField(max_length=50, verbose_name='訂單狀態')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_maintenance.member', verbose_name='會員編號')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, verbose_name='方法')),
                ('credit_number', models.CharField(max_length=50, null=True, verbose_name='信用卡號碼')),
                ('credit_private', models.CharField(max_length=50, null=True, verbose_name='授權碼')),
                ('credit_date_year', models.DateField(max_length=50, null=True, verbose_name='期限年')),
                ('credit_date_month', models.DateField(max_length=50, null=True, verbose_name='期限月')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='餐點數量')),
                ('discount', models.IntegerField(verbose_name='折扣')),
                ('subtotal', models.IntegerField(verbose_name='小計')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品編號')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='購物車編號')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品編號')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_maintenance.store', verbose_name='店家編號')),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_maintenance.member')),
            ],
        ),
    ]
