# Generated by Django 4.1.10 on 2023-10-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(null=True, verbose_name='完成時間'),
        ),
    ]
