# Generated by Django 4.1.10 on 2023-10-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sid',
        ),
    ]
