# Generated by Django 4.1.10 on 2023-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_cart_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='添加時間'),
        ),
    ]
