# Generated by Django 4.1.10 on 2023-10-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_complete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderfoods', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpayment', to='order.order', unique=True),
        ),
    ]
