# Generated by Django 4.1.10 on 2023-10-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderpayment_oid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordercheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.CharField(max_length=10, verbose_name='核准碼')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercheck', to='order.order', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(blank=True, max_length=100, verbose_name='取消理由')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercancel', to='order.order', unique=True)),
            ],
        ),
    ]
